import { request } from '@/utils/request'

export const getServiceItems = (params) => request.get('/orders/service-items', { params })
export const updateServiceItemStatus = (id, status) => request.patch(`/orders/service-items/${id}`, { status })
export const getShopProducts = (params) => request.get('/orders/products', { params })
export const getCustomItems = (params) => request.get('/orders/custom-items', { params })
export const createCustomItem = (data) => request.post('/orders/custom-items', data)
export const deleteCustomItem = (id) => request.delete(`/orders/custom-items/${id}`)
export const getHangTickets = () => request.get('/orders/hang')
export const createOrder = (data) => request.post('/orders', data)
export const getOrderList = (params) => request.get('/orders', { params })
export const getOrderDetail = (id) => request.get(`/orders/${id}`)
export const deleteOrder = (id, data) => request.delete(`/orders/${id}`, { data })
export const redeemHangTicket = (id) => request.post(`/orders/${id}/redeem`)
export const getInvoice = (orderNo) => request.get(`/orders/invoice/${orderNo}`)
